version: "3.4"

services:
  panopli-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_USER: clientPoc
      MONGO_PASSWORD: password
    restart: unless-stopped
    expose:
      - 5000
    network_mode: bridge
