version: '3.4'

services:
  db:
    image: mongo
    container_name: panopli-db
    volumes:
      - ./data/mongodb:/data/db
      - ./data/mongodb-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD:-Secr3t!}
    restart: unless-stopped

  api:
    container_name: panopli-backend
    build:
      context: ../../backend
    ports:
      - "5000:5000"
    environment:
      MONGO_USER: client
      MONGO_PASSWORD: password
    restart: unless-stopped
    depends_on:
      - db

  client:
    build:
      context: ../../frontend
    container_name: panopli-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - api

  reverse-proxy:
    build:
      context: ./reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - api
      - db
