version: '3.4'

services:
  panopli-db:
    image: mongo
    container_name: panopli-db
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
      - ./data/mongodb-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD:-Secr3t!}
    network_mode: bridge
    restart: unless-stopped

  panopli-backend:
    container_name: panopli-backend
    build:
      context: ../../backend
    ports:
      - "5000:5000"
    environment:
      MONGO_USER: clientPoc
      MONGO_PASSWORD: password
    restart: unless-stopped
    network_mode: bridge
    depends_on:
      - panopli-db

  panopli-frontend:
    build:
      context: ../../frontend
    container_name: panopli-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    network_mode: bridge
    depends_on:
      - panopli-backend
