apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  volumes:
    - name: mongo-storage
      persistentVolumeClaim:
        claimName: mongo-pvc
  containers:
    - name: mongodb
      image: mongo
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo
              key: adminName

        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: adminPass

      ports:
        - containerPort: 27017
          name: mongodb-port
      volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
